"""Optional DHCP-mode support, deliberately isolated from gateway business logic."""

from __future__ import annotations

import argparse
from pathlib import Path
import tempfile

from .config import GatewayConfig, load


def render_dnsmasq_config(config: GatewayConfig) -> str:
    """Render a DHCP-only dnsmasq configuration for the dedicated Ethernet link."""
    network = config.network
    if network.mode != "dhcp":
        raise ValueError("DHCP configuration is unavailable while network.mode is static")
    assert network.interface and network.subnet_cidr and network.dhcp_range_start and network.dhcp_range_end
    import ipaddress

    netmask = str(ipaddress.ip_network(network.subnet_cidr, strict=True).netmask)
    return "\n".join(
        (
            "# Generated by neurobridge-dhcp-config; do not edit.",
            f"interface={network.interface}",
            "bind-interfaces",
            "port=0",
            "user=neurobridge",
            "dhcp-authoritative",
            f"dhcp-range={network.dhcp_range_start},{network.dhcp_range_end},{netmask},{network.dhcp_lease_time}",
            f"dhcp-option=option:router,{config.server.host}",
            "log-dhcp",
            "log-facility=/var/log/neurobridge/dhcp.log",
            "",
        )
    )


def write_dnsmasq_config(config: GatewayConfig, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=output.parent, delete=False) as file:
        file.write(render_dnsmasq_config(config))
        temporary = Path(file.name)
    temporary.chmod(0o640)
    temporary.replace(output)


def main() -> None:
    parser = argparse.ArgumentParser(description="Render the optional NeuroBridge DHCP service configuration")
    parser.add_argument("--config", required=True)
    parser.add_argument("--check-enabled", action="store_true")
    parser.add_argument("--output")
    args = parser.parse_args()
    config = load(args.config)
    if args.check_enabled:
        raise SystemExit(0 if config.network.mode == "dhcp" else 1)
    if not args.output:
        parser.error("--output is required unless --check-enabled is used")
    write_dnsmasq_config(config, Path(args.output))
