#!/usr/bin/env bash
# Build one self-contained, network-free Galaxy Kylin source updater.
set -euo pipefail

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
default_output="$repo_root/.runtime/packages/neurobridge-kylin-offline-update.run"
output_path=$default_output
branch=

usage() {
  cat <<EOF
Usage: ./tools/build-kylin-offline-update.sh [options]

Create one executable file containing the committed Git branch needed by an
offline Galaxy Kylin computer. The generated runner never contacts a remote.

Options:
  --branch NAME   Local branch to package (default: current branch)
  --output FILE   Output .run path (default: $default_output)
  -h, --help      Show this help

The source worktree and index must be clean. Commit and test changes first.
Transfer only the resulting .run file to the target project root and run:
  bash neurobridge-kylin-offline-update.run
EOF
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --branch)
      [[ $# -ge 2 ]] || fail "--branch requires a value"
      branch=$2
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || fail "--output requires a value"
      output_path=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) fail "Unknown option: $1" ;;
  esac
done

[[ -d $repo_root/.git && ! -L $repo_root/.git ]] || fail "Not a Git checkout: $repo_root"
command -v git >/dev/null 2>&1 || fail "git is required on the development computer"
if [[ -z $branch ]]; then
  branch=$(git -C "$repo_root" symbolic-ref --quiet --short HEAD) \
    || fail "Detached HEAD: specify an existing local branch with --branch"
fi
git -C "$repo_root" show-ref --verify --quiet "refs/heads/$branch" \
  || fail "Local branch does not exist: $branch"
git -C "$repo_root" diff --quiet \
  || fail "Source worktree has tracked changes. Commit and test them before packaging."
git -C "$repo_root" diff --cached --quiet \
  || fail "Source index has staged changes. Commit them before packaging."

revision=$(git -C "$repo_root" rev-parse "refs/heads/$branch")
short_revision=$(git -C "$repo_root" rev-parse --short=12 "$revision")
runtime_build_dir="$repo_root/.runtime/package-build"
mkdir -p -- "$runtime_build_dir" "$(dirname "$output_path")"
bundle_path=$(mktemp "$runtime_build_dir/.kylin-offline-update.XXXXXX.bundle")
temporary_output="${output_path}.tmp.$$"

cleanup() {
  [[ ! -f $bundle_path ]] || unlink "$bundle_path"
  [[ ! -f $temporary_output ]] || unlink "$temporary_output"
}
trap cleanup EXIT

git -C "$repo_root" bundle create "$bundle_path" "refs/heads/$branch"
git -C "$repo_root" bundle verify "$bundle_path" >/dev/null
if command -v sha256sum >/dev/null 2>&1; then
  bundle_sha256=$(sha256sum "$bundle_path" | awk '{print $1}')
else
  bundle_sha256=$(shasum -a 256 "$bundle_path" | awk '{print $1}')
fi

{
  printf '#!/usr/bin/env bash\n'
  printf 'offline_branch=%q\n' "$branch"
  printf 'offline_revision=%q\n' "$revision"
  printf 'offline_short_revision=%q\n' "$short_revision"
  printf 'offline_bundle_sha256=%q\n' "$bundle_sha256"
  cat <<'RUNNER'
# Generated by tools/build-kylin-offline-update.sh. The Git bundle is appended
# below __NEUROBRIDGE_GIT_BUNDLE__. Do not edit this generated file.
set -euo pipefail

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

ask_yes_no() {
  local prompt=$1 answer
  while true; do
    printf '%s [yes/no]: ' "$prompt"
    IFS= read -r answer || return 1
    case $answer in
      [Yy][Ee][Ss]|[Yy]) return 0 ;;
      [Nn][Oo]|[Nn]) return 1 ;;
      *) printf '请输入 yes 或 no。\n' ;;
    esac
  done
}

usage() {
  cat <<EOF
Usage: bash neurobridge-kylin-offline-update.run [--project-dir DIR]

Install NeuroBridge branch $offline_branch at revision $offline_short_revision
from the Git bundle embedded in this one file. No network access, git fetch
from origin, or git pull is performed. Existing .runtime and ignored field
data remain untouched.
EOF
}

project_dir=
while [[ $# -gt 0 ]]; do
  case $1 in
    --project-dir)
      [[ $# -ge 2 ]] || fail "--project-dir requires a value"
      project_dir=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) fail "Unknown option: $1" ;;
  esac
done

[[ ${EUID:-$(id -u)} -ne 0 ]] || fail \
  "不要使用 sudo；请直接执行：bash neurobridge-kylin-offline-update.run"
runner_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
if [[ -z $project_dir ]]; then
  if [[ -f $runner_dir/pyproject.toml ]]; then
    project_dir=$runner_dir
  elif [[ -f $PWD/pyproject.toml ]]; then
    project_dir=$(pwd -P)
  else
    fail "请把本文件放入 NeuroBridge 项目根目录，或使用 --project-dir 指定项目。"
  fi
else
  project_dir=$(cd "$project_dir" && pwd -P) || fail "项目目录不存在：$project_dir"
fi

[[ -n $project_dir && $project_dir != / ]] || fail "不安全的项目目录：$project_dir"
[[ -f $project_dir/pyproject.toml ]] || fail "目标不是 NeuroBridge 项目：$project_dir"
[[ -d $project_dir/.git && ! -L $project_dir/.git ]] || fail \
  "离线更新要求现有项目包含真实 .git 目录：$project_dir"

current_uid=$(id -u)
current_gid=$(id -g)
permission_problem=false
[[ -w $project_dir/.git ]] || permission_problem=true
[[ ! -e $project_dir/.git/index || -w $project_dir/.git/index ]] || permission_problem=true
foreign_path=$(find "$project_dir" -xdev ! -uid "$current_uid" -print -quit 2>/dev/null || true)
[[ -z $foreign_path ]] || permission_problem=true
if [[ $permission_problem == true ]]; then
  printf '检测到项目权限异常：%s\n' "${foreign_path:-$project_dir/.git}"
  ask_yes_no "是否只修复该项目的所有权和 Git 写权限？" \
    || fail "已取消；项目未修改。"
  sudo chown -R --no-dereference "$current_uid:$current_gid" "$project_dir"
  sudo find "$project_dir/.git" -type d -exec chmod u+rwx {} +
  sudo find "$project_dir/.git" -type f -exec chmod u+rw {} +
fi

[[ -w $project_dir/.git ]] || fail "项目 .git 仍不可写。"
[[ ! -e $project_dir/.git/index || -w $project_dir/.git/index ]] || fail \
  "项目 .git/index 仍不可写。"
[[ ! -e $project_dir/.git/index.lock ]] || fail \
  "发现 .git/index.lock；确认没有 Git 进程后由开发人员处理，本程序不会自动删除。"

mkdir -p -- "$project_dir/.runtime/logs" "$project_dir/.runtime/offline-update"
update_log="$project_dir/.runtime/logs/kylin-offline-update-$(date -u +%Y%m%dT%H%M%SZ)-$$.log"
touch "$update_log"
chmod 0600 "$update_log" 2>/dev/null || true
exec > >(tee -a "$update_log") 2>&1
printf 'project=%s\nlog=%s\nofflineBranch=%s\nofflineRevision=%s\nnetworkAccessAttempted=false\n' \
  "$project_dir" "$update_log" "$offline_branch" "$offline_revision"

command -v git >/dev/null 2>&1 || fail "目标电脑缺少 git，无法安全应用离线版本。"
command -v sha256sum >/dev/null 2>&1 || fail "目标电脑缺少 sha256sum。"
git -C "$project_dir" diff --quiet \
  || fail "项目存在未提交的已跟踪文件修改。为避免覆盖，离线更新已停止。"
git -C "$project_dir" diff --cached --quiet \
  || fail "项目存在已暂存修改。为避免覆盖，离线更新已停止。"

payload_line=$(awk '/^__NEUROBRIDGE_GIT_BUNDLE__$/ { print NR + 1; exit }' "$0")
[[ $payload_line =~ ^[0-9]+$ ]] || fail "未找到内置 Git bundle。"
bundle_path="$project_dir/.runtime/offline-update/.bundle.$$"
cleanup_bundle() {
  case $bundle_path in
    "$project_dir"/.runtime/offline-update/.bundle.*)
      [[ ! -f $bundle_path ]] || unlink "$bundle_path"
      ;;
  esac
}
trap cleanup_bundle EXIT
tail -n "+$payload_line" "$0" >"$bundle_path"
actual_sha256=$(sha256sum "$bundle_path" | awk '{print $1}')
[[ $actual_sha256 == "$offline_bundle_sha256" ]] || fail \
  "离线包校验失败：expected=$offline_bundle_sha256 actual=$actual_sha256"
git -C "$project_dir" bundle verify "$bundle_path" >/dev/null \
  || fail "内置 Git bundle 验证失败。"

offline_ref="refs/remotes/neurobridge-offline/$offline_branch"
git -C "$project_dir" fetch --no-tags "$bundle_path" \
  "refs/heads/$offline_branch:$offline_ref"
current_branch=$(git -C "$project_dir" symbolic-ref --quiet --short HEAD 2>/dev/null || true)
printf 'currentBranch=%s\n' "${current_branch:-detached}"
if [[ $current_branch != "$offline_branch" ]]; then
  printf '离线包将从当前分支 %s 切换到 %s。\n' "${current_branch:-detached}" "$offline_branch"
  ask_yes_no "是否继续切换并安装离线版本？" || fail "已取消；工作分支未切换。"
  if git -C "$project_dir" show-ref --verify --quiet "refs/heads/$offline_branch"; then
    git -C "$project_dir" checkout "$offline_branch"
  else
    git -C "$project_dir" checkout -b "$offline_branch" "$offline_ref"
  fi
fi
git -C "$project_dir" merge --ff-only "$offline_ref" \
  || fail "当前分支无法快进到离线版本；请把日志交给开发人员，不要强制覆盖。"
installed_revision=$(git -C "$project_dir" rev-parse HEAD)
[[ $installed_revision == "$offline_revision" ]] || fail \
  "安装后的 revision 不符合离线包：expected=$offline_revision actual=$installed_revision"
printf 'branch=%s\nrevision=%s\nbundleSha256=%s\ninstalledAt=%s\n' \
  "$offline_branch" "$offline_revision" "$offline_bundle_sha256" \
  "$(date --iso-8601=seconds 2>/dev/null || date)" \
  >"$project_dir/.runtime/offline-update/current.txt"
printf '离线更新完成：branch=%s revision=%s\n' "$offline_branch" "$offline_short_revision"
printf '未访问网络；.runtime、现场配置和录制数据均已保留。\n'
cleanup_bundle
trap - EXIT
exec bash "$project_dir/linux/neurobridge-kylin-bootstrap.sh"
exit 0
__NEUROBRIDGE_GIT_BUNDLE__
RUNNER
  cat "$bundle_path"
} >"$temporary_output"

chmod 0755 "$temporary_output"
mv -f -- "$temporary_output" "$output_path"
if command -v sha256sum >/dev/null 2>&1; then
  runner_sha256=$(sha256sum "$output_path" | awk '{print $1}')
else
  runner_sha256=$(shasum -a 256 "$output_path" | awk '{print $1}')
fi
printf 'Offline updater created: %s\n' "$output_path"
printf 'branch=%s\nrevision=%s\nbundleSha256=%s\nrunnerSha256=%s\n' \
  "$branch" "$revision" "$bundle_sha256" "$runner_sha256"
printf 'Transfer this one file to the target project root and run:\n'
printf '  bash %s\n' "$(basename "$output_path")"
